# Generated by Django 5.0.4 on 2024-04-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('room', models.CharField(choices=[('2 ST', '2 seater'), ('3 ST', '3 seater'), ('4 ST', '4 seater')], max_length=20)),
                ('arrival_date', models.DateField()),
                ('leave_date', models.DateField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
